name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'      # change to 'pnpm' or 'yarn' if needed

      - name: Install deps
        run: npm ci         # pnpm i --frozen-lockfile | yarn --frozen-lockfile

      - name: Lint
        run: npm run lint --if-present

      - name: Tests
        run: npm test --if-present

      - name: Typecheck
        run: npm run typecheck --if-present

      - name: Build
        run: npm run build --if-present
